### ISSUE TITLE
Build does not fail using gcc/g++ 4.9+

### ISSUE THREAD

**Issue by gustavovelascoh** [erik78se/opencv-installers#1]
HI, there the installation guide states that compiling OpenCV 3.1.0 using gcc and g++ 4.9+ fails, but I build it using version 5.3 on Ubuntu 16.04 and it works.

**Comment by erik78se** [comment]
Thanx! Although the guide is tweaked on Ubuntu 14,15... I'll add it as a comment. Thanx!
