### ISSUE TITLE
Fails to get opencv

### ISSUE THREAD

**Issue by karanchawla** [erik78se/opencv-installers#4]
`$ git clone gi@github.com:Iteez/opencv.git
Cloning into 'opencv'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

Hi, trying to install opencv using this method and it fails at this step. Also can't find the aforementioned repository, maybe that's the problem? 
Thanks.

**Comment by erik78se** [comment]
You have misspelled "git" in your clone command.

Cheers!

Den 23 sep 2016 08:43 skrev "Karan Chawla" notifications@github.com:

**Comment by karanchawla** [comment]
Yes I figured, Thanks :D
